version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - jetersen
- directory: /
  package-ecosystem: github-actions
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
    - jetersen
