# Configuration for Release Drafter: https://github.com/release-drafter/release-drafter

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: ":boom: Breaking changes"
    labels:
      - breaking
  - title: ":fire: Removed"
    label: removed
  - title: ⚠️ Deprecated
    label: deprecated
  - title: ":sparkles: New features and improvements"
    labels:
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 📝 Documentation updates
    label: documentation
  - title: 👻 Maintenance
    label: chore
  - title: 🚦 Tests
    labels:
      - test
  - title: 📦 Dependency updates
    label: dependencies
exclude-labels:
  - skip-changelog

template: |
  <!-- Optional: add a release summary here -->
  $CHANGES

replacers:
  - search: '@dependabot-preview'
    replace: '@dependabot'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
